// <auto-generated />
using System;
using KaloriTakipSistemi.UI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaloriTakipSistemi.UI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KaloriTakipSistemi.UI.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HesapDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Yas")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("KaloriTakipSistemi.UI.Models.KullaniciYemek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int>("OgunId")
                        .HasColumnType("int");

                    b.Property<int>("YemekId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YemekTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("OgunId");

                    b.HasIndex("YemekId");

                    b.ToTable("KullaniciYemekler");
                });

            modelBuilder.Entity("KaloriTakipSistemi.UI.Models.Ogun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ogunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Sabah"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Öğle"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Akşam"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Ara Öğün"
                        });
                });

            modelBuilder.Entity("KaloriTakipSistemi.UI.Models.Yemek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kalori")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Yemekler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Kahvaltı Tabağı",
                            Kalori = 450.0
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Menemen",
                            Kalori = 250.0
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Sucuklu Yumurta",
                            Kalori = 300.0
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Peynirli Omlet",
                            Kalori = 280.0
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Avokadolu Tost",
                            Kalori = 320.0
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Mercimek Çorbası",
                            Kalori = 120.0
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Ezogelin Çorbası",
                            Kalori = 150.0
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Tavuk Sote",
                            Kalori = 400.0
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Etli Nohut",
                            Kalori = 450.0
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Kuru Fasulye",
                            Kalori = 430.0
                        },
                        new
                        {
                            Id = 11,
                            Ad = "Izgara Köfte",
                            Kalori = 350.0
                        },
                        new
                        {
                            Id = 12,
                            Ad = "Pilav Üstü Tavuk",
                            Kalori = 500.0
                        },
                        new
                        {
                            Id = 13,
                            Ad = "Sebzeli Bulgur Pilavı",
                            Kalori = 300.0
                        },
                        new
                        {
                            Id = 14,
                            Ad = "Fırında Somon",
                            Kalori = 370.0
                        },
                        new
                        {
                            Id = 15,
                            Ad = "Zeytinyağlı Taze Fasulye",
                            Kalori = 220.0
                        },
                        new
                        {
                            Id = 16,
                            Ad = "Zeytinyağlı Enginar",
                            Kalori = 200.0
                        },
                        new
                        {
                            Id = 17,
                            Ad = "Fırında Tavuk But",
                            Kalori = 380.0
                        },
                        new
                        {
                            Id = 18,
                            Ad = "Fırında Kabak Mücver",
                            Kalori = 250.0
                        },
                        new
                        {
                            Id = 19,
                            Ad = "Mantı",
                            Kalori = 550.0
                        },
                        new
                        {
                            Id = 20,
                            Ad = "Lazanya",
                            Kalori = 600.0
                        },
                        new
                        {
                            Id = 21,
                            Ad = "Spagetti Bolognese",
                            Kalori = 580.0
                        },
                        new
                        {
                            Id = 22,
                            Ad = "Tavuklu Sezar Salata",
                            Kalori = 350.0
                        },
                        new
                        {
                            Id = 23,
                            Ad = "Ton Balıklı Salata",
                            Kalori = 300.0
                        },
                        new
                        {
                            Id = 24,
                            Ad = "Çoban Salata",
                            Kalori = 100.0
                        },
                        new
                        {
                            Id = 25,
                            Ad = "Yeşil Mercimek Salatası",
                            Kalori = 250.0
                        },
                        new
                        {
                            Id = 26,
                            Ad = "Acılı Ezme",
                            Kalori = 80.0
                        },
                        new
                        {
                            Id = 27,
                            Ad = "Humus",
                            Kalori = 180.0
                        },
                        new
                        {
                            Id = 28,
                            Ad = "Patates Kızartması",
                            Kalori = 400.0
                        },
                        new
                        {
                            Id = 29,
                            Ad = "Fırında Patates",
                            Kalori = 220.0
                        },
                        new
                        {
                            Id = 30,
                            Ad = "Karışık Pizza (orta dilim)",
                            Kalori = 280.0
                        },
                        new
                        {
                            Id = 31,
                            Ad = "Tavuk Döner Dürüm",
                            Kalori = 520.0
                        },
                        new
                        {
                            Id = 32,
                            Ad = "Et Döner Porsiyon",
                            Kalori = 550.0
                        },
                        new
                        {
                            Id = 33,
                            Ad = "Burger (Klasik)",
                            Kalori = 600.0
                        },
                        new
                        {
                            Id = 34,
                            Ad = "Lahmacun",
                            Kalori = 220.0
                        },
                        new
                        {
                            Id = 35,
                            Ad = "Pide (Kıymalı)",
                            Kalori = 500.0
                        },
                        new
                        {
                            Id = 36,
                            Ad = "Karnıyarık",
                            Kalori = 380.0
                        },
                        new
                        {
                            Id = 37,
                            Ad = "İmam Bayıldı",
                            Kalori = 250.0
                        },
                        new
                        {
                            Id = 38,
                            Ad = "Zeytinyağlı Barbunya",
                            Kalori = 230.0
                        },
                        new
                        {
                            Id = 39,
                            Ad = "Yoğurtlu Kabak",
                            Kalori = 180.0
                        },
                        new
                        {
                            Id = 40,
                            Ad = "Taze Börülce",
                            Kalori = 210.0
                        },
                        new
                        {
                            Id = 41,
                            Ad = "Kıymalı Makarna",
                            Kalori = 530.0
                        },
                        new
                        {
                            Id = 42,
                            Ad = "Fırın Tavuklu Makarna",
                            Kalori = 480.0
                        },
                        new
                        {
                            Id = 43,
                            Ad = "Sebzeli Noodle",
                            Kalori = 350.0
                        },
                        new
                        {
                            Id = 44,
                            Ad = "Şehriyeli Tavuk Çorbası",
                            Kalori = 130.0
                        },
                        new
                        {
                            Id = 45,
                            Ad = "Domates Çorbası",
                            Kalori = 110.0
                        },
                        new
                        {
                            Id = 46,
                            Ad = "Yoğurtlu Karnabahar",
                            Kalori = 190.0
                        },
                        new
                        {
                            Id = 47,
                            Ad = "Zeytinyağlı Pırasa",
                            Kalori = 210.0
                        },
                        new
                        {
                            Id = 48,
                            Ad = "Çılbır",
                            Kalori = 270.0
                        },
                        new
                        {
                            Id = 49,
                            Ad = "Kısır",
                            Kalori = 300.0
                        },
                        new
                        {
                            Id = 50,
                            Ad = "Mücver",
                            Kalori = 240.0
                        });
                });

            modelBuilder.Entity("KaloriTakipSistemi.UI.Models.Yonetici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoneticiAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yoneticiler");
                });

            modelBuilder.Entity("KaloriTakipSistemi.UI.Models.KullaniciYemek", b =>
                {
                    b.HasOne("KaloriTakipSistemi.UI.Models.Kullanici", "Kullanici")
                        .WithMany("KullaniciYemek")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KaloriTakipSistemi.UI.Models.Ogun", "Ogun")
                        .WithMany("KullaniciYemek")
                        .HasForeignKey("OgunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KaloriTakipSistemi.UI.Models.Yemek", "Yemek")
                        .WithMany("KullaniciYemeks")
                        .HasForeignKey("YemekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Ogun");

                    b.Navigation("Yemek");
                });

            modelBuilder.Entity("KaloriTakipSistemi.UI.Models.Kullanici", b =>
                {
                    b.Navigation("KullaniciYemek");
                });

            modelBuilder.Entity("KaloriTakipSistemi.UI.Models.Ogun", b =>
                {
                    b.Navigation("KullaniciYemek");
                });

            modelBuilder.Entity("KaloriTakipSistemi.UI.Models.Yemek", b =>
                {
                    b.Navigation("KullaniciYemeks");
                });
#pragma warning restore 612, 618
        }
    }
}
